version: '3'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restneer
    networks:
        - backend
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
networks:       
    backend:
        driver: bridge