version: '3'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_restneer
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:5.0.0
    command: redis-server --requirepass 123456  
    ports:
      - 6379:6379